from django.urls import path

from apps.ai_sms.views import (
    SmsAgentDialAnswerView,
    SmsAgentDialBridgeStatusView,
    SmsAgentDialRecordingView,
    SmsAgentDialStatusView,
    SmsConversationDetailView,
    SmsConversationListView,
    SmsWebhookView,
    StartMinorSmsConversationView,
    StartSmsConversationView,
)

urlpatterns = [
    path(
        "outbound/",
        StartSmsConversationView.as_view(),
        name="ai-sms-outbound",
    ),
    path(
        "minor/outbound/",
        StartMinorSmsConversationView.as_view(),
        name="ai-sms-minor-outbound",
    ),
    path(
        "conversations/",
        SmsConversationListView.as_view(),
        name="ai-sms-conversation-list",
    ),
    path(
        "conversations/<str:lookup>/",
        SmsConversationDetailView.as_view(),
        name="ai-sms-conversation-detail",
    ),
    path(
        "webhook/",
        SmsWebhookView.as_view(),
        name="ai-sms-webhook",
    ),
    path(
        "agent-dial/answer/<str:chat_id>/",
        SmsAgentDialAnswerView.as_view(),
        name="ai-sms-agent-dial-answer",
    ),
    path(
        "agent-dial/bridge-status/<str:chat_id>/",
        SmsAgentDialBridgeStatusView.as_view(),
        name="ai-sms-agent-dial-bridge-status",
    ),
    path(
        "agent-dial/status/<str:chat_id>/",
        SmsAgentDialStatusView.as_view(),
        name="ai-sms-agent-dial-status",
    ),
    path(
        "agent-dial/recording/<str:chat_id>/",
        SmsAgentDialRecordingView.as_view(),
        name="ai-sms-agent-dial-recording",
    ),
]
